CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "e_mail" varchar NOT NULL,
  "name" varchar,
  "surname" varchar,
  "hash_password" varchar
);

CREATE TABLE "room" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "user_id" int NOT NULL
);

CREATE TABLE "device" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "room_id" int NOT NULL,
  "name" varchar NOT NULL,
  "type" varchar NOT NULL,
  "state" bool NOT NULL DEFAULT false,
  "ip" varchar NOT NULL,
  "time" varchar,
  "alarm_time" varchar,
  "alarm_lamp" bool NOT NULL DEFAULT false
);

ALTER TABLE "room" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "device" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "device" ADD FOREIGN KEY ("room_id") REFERENCES "room" ("id");
