CREATE TABLE "user"
(
    "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "e_mail"        varchar NOT NULL,
    "name"          varchar,
    "surname"       varchar,
    "hash_password" varchar
);

CREATE TABLE "room"
(
    "id"      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"    varchar NOT NULL,
    "user_id" int     NOT NULL
);

ALTER TABLE "room"
    ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;
